160 replace black with ruff format
dribia/driconfig pull request #166
Opened 2024-05-14 07:06 UTC by juliasalaprat

2024-05-14 09:08 UTC, airibarne requested changes

2024-05-14 09:08 UTC, airibarne commented on scripts/lint.sh
> +poetry run ruff format driconfig tests
@juliasalaprat afegir `--check` al final perquè només comprovi i no modifiqui

2024-05-14 09:08 UTC, airibarne commented on pyproject.toml
> -    "E501",  # line too long, handled by black
@juliasalaprat [aquí](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules) hi ha una sèrie de recomanacions de `ruff` mateix, que diuen que ignorem algunes regles del linter si utilitzem el formatter

2024-05-14 09:08 UTC, airibarne commented on poetry.lock
@juliasalaprat en ppi mai modifiquem a mà el `poetry.lock`, ha d'estar sempre tal qual surt d'un `poetry lock`, executa aquesta comanda i tal qual surti el commiteges. Si hi ha coses de Black, serà pq alguna dependència l'instal·la per sota, però això is OK

2024-05-16 06:33 UTC, juliasalaprat commented on pyproject.toml
> -    "E501",  # line too long, handled by black
dius que cal afegirles totes al ignore?

2024-05-16 07:45 UTC, airibarne commented on pyproject.toml
> -    "E501",  # line too long, handled by black
@juliasalaprat sorry, ara veig això. Sí, afegim-les totes, pq ho recomanen ells mateixos

2024-05-16 10:12 UTC, airibarne approved these changes

2024-05-16 10:12 UTC, merged